# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05e0a01f8906a1181f450e7876bc377b8e820d7aad1a5672cc343c501537bcc993335a001129bbf209a4ed2aa2f70fdb9c65e275fbd6242fa6e24822cd8a0bda

test:
  secret_key_base: 9ab9b869704d58dee1e9173ea2d4dcb571f25d8503661ef3312b59be7ebdb29addc9eca6823787fcd81d9eea7a54f5a8a82e2cd90b00e67f3df05eeac032fdc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
